server.port=8082
spring.application.name=doctor-api

# SSL Configuration (HTTPS)
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=qwertyuiop
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=doctor-api

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/doctor-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.ru.platik777.doctorapi=INFO
logging.level.ca.uhn.fhir=INFO